### ISSUE TITLE
Everyone is treated equally even if you're "Violating this Code of Conduct" makes the entire thing pointless

### ISSUE THREAD

**Issue by euclaise** [engineeror/KissCoC#2]
One of given examples of people that are treated equally is those who are "Violating this Code of Conduct".  That makes the entire CoC pointless, as people can't be penalized (or even warned) for violating it.

**Comment by engineeror** [comment]
Sorry, it doesn't make sense to me.

Are you saying that _"people can't be penalized (or even warned) for violating it"_ _"equally and respectfully"_? I don't see how not calling someone a butthole/whatever who's just violated the CoC, _"makes the entire CoC pointless"_.

**Comment by euclaise** [comment]
>Absolutely everyone, without any exceptions whatsoever, is treated equally and respectfully

*Arguably*, banning someone for violating it isn't being respectful to them

**Comment by engineeror** [comment]
You're right. According to [the dictionary](https://www.merriam-webster.com/dictionary/respect), _respect_ means _to consider worthy of high regard_. And banned people usually aren't considered to be _worthy of high regard_. So we need to replace _respect_ with some more appropriate word, or maybe remove it altogether?

**Comment by engineeror** [comment]
How about
> Absolutely everyone, without any exceptions whatsoever, is treated equally and _courteously_

**Comment by euclaise** [comment]
You could try to argue that equal treatment would also constitute not banning them, but that certainly is better.

**Comment by engineeror** [comment]
I think equal treatment implies that anyone can be banned if their behavior calls for it. Be bad - get banned, be good - we'll be fine.

We might need a 4th paragraph describing/clarifying what happens when one misconducts

**Comment by euclaise** [comment]
That's probably a good idea.  I might write something up later today for that.
